<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>org.apache.hbase</groupId>
    <artifactId>hbase-shaded</artifactId>
    <version>${revision}</version>
    <relativePath>../pom.xml</relativePath>
  </parent>
  <artifactId>hbase-backup-shaded</artifactId>
  <name>Apache HBase - shaded - backup (with hadoop bundled)</name>

  <properties>
    <phoenix.version>5.2.1</phoenix.version>
    <hbase.hadoop3.version>${revision}</hbase.hadoop3.version>
    <jersey-core.version>1.19.4</jersey-core.version>
  </properties>

  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>org.apache.hbase</groupId>
        <artifactId>hbase-backup</artifactId>
        <version>${hbase.hadoop3.version}</version>
      </dependency>
      <dependency>
        <groupId>org.apache.hbase</groupId>
        <artifactId>hbase-client</artifactId>
        <version>${hbase.hadoop3.version}</version>
      </dependency>
      <dependency>
        <groupId>org.apache.hbase</groupId>
        <artifactId>hbase-server</artifactId>
        <version>${hbase.hadoop3.version}</version>
      </dependency>
      <dependency>
        <groupId>org.apache.hbase</groupId>
        <artifactId>hbase-mapreduce</artifactId>
        <version>${revision}</version>
      </dependency>
      <dependency>
        <groupId>org.apache.hbase</groupId>
        <artifactId>hbase-shaded-mapreduce</artifactId>
        <version>${revision}</version>
      </dependency>
      <dependency>
        <groupId>org.apache.hbase</groupId>
        <artifactId>hbase-common</artifactId>
        <version>${hbase.hadoop3.version}</version>
      </dependency>
      <dependency>
        <groupId>org.apache.hbase</groupId>
        <artifactId>hbase-http</artifactId>
        <version>${hbase.hadoop3.version}</version>
      </dependency>
      <dependency>
        <groupId>org.apache.hbase</groupId>
        <artifactId>hbase-logging</artifactId>
        <version>${hbase.hadoop3.version}</version>
      </dependency>
      <dependency>
        <groupId>org.apache.hbase</groupId>
        <artifactId>hbase-protocol</artifactId>
        <version>${hbase.hadoop3.version}</version>
      </dependency>
      <dependency>
        <groupId>org.apache.hbase</groupId>
        <artifactId>hbase-protocol-shaded</artifactId>
        <version>${hbase.hadoop3.version}</version>
      </dependency>
      <dependency>
        <groupId>org.apache.hbase</groupId>
        <artifactId>hbase-procedure</artifactId>
        <version>${hbase.hadoop3.version}</version>
      </dependency>
      <dependency>
        <groupId>org.apache.hbase</groupId>
        <artifactId>hbase-zookeeper</artifactId>
        <version>${hbase.hadoop3.version}</version>
      </dependency>
      <dependency>
        <groupId>org.apache.hbase</groupId>
        <artifactId>hbase-replication</artifactId>
        <version>${hbase.hadoop3.version}</version>
      </dependency>
      <dependency>
        <groupId>org.apache.hbase</groupId>
        <artifactId>hbase-metrics</artifactId>
        <version>${hbase.hadoop3.version}</version>
      </dependency>
      <dependency>
        <groupId>org.apache.hbase</groupId>
        <artifactId>hbase-metrics-api</artifactId>
        <version>${hbase.hadoop3.version}</version>
      </dependency>
      <dependency>
        <groupId>org.apache.hbase</groupId>
        <artifactId>hbase-asyncfs</artifactId>
        <version>${hbase.hadoop3.version}</version>
      </dependency>
      <dependency>
        <groupId>org.apache.hbase</groupId>
        <artifactId>hbase-hadoop-compat</artifactId>
        <version>${hbase.hadoop3.version}</version>
      </dependency>
      <dependency>
        <groupId>org.apache.hbase</groupId>
        <artifactId>hbase-hadoop2-compat</artifactId>
        <version>${hbase.hadoop3.version}</version>
      </dependency>
    </dependencies>
  </dependencyManagement>

  <dependencies>
    <dependency>
      <groupId>org.apache.hbase</groupId>
      <artifactId>hbase-backup</artifactId>
      <version>${hbase.hadoop3.version}</version>
      <exclusions>
        <exclusion>
          <groupId>org.apache.tomcat</groupId>
          <artifactId>tomcat-jasper</artifactId>
        </exclusion>
        <exclusion>
          <groupId>javax.servlet</groupId>
          <artifactId>javax.servlet-api</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
    <dependency>
      <groupId>org.apache.hadoop</groupId>
      <artifactId>hadoop-mapreduce-client-jobclient</artifactId>
      <version>${hadoop.version}</version>
    </dependency>
    <dependency>
      <groupId>com.sun.jersey</groupId>
      <artifactId>jersey-core</artifactId>
      <version>${jersey-core.version}</version>
    </dependency>
    <dependency>
      <groupId>javax.ws.rs</groupId>
      <artifactId>javax.ws.rs-api</artifactId>
    </dependency>
    <dependency>
      <groupId>org.apache.phoenix</groupId>
      <artifactId>phoenix-mapreduce-byo-shaded-hbase-hbase-2.6</artifactId>
      <version>${phoenix.version}</version>
    </dependency>
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-site-plugin</artifactId>
        <configuration>
          <skip>true</skip>
        </configuration>
      </plugin>
      <plugin>
        <artifactId>maven-assembly-plugin</artifactId>
        <configuration>
          <skipAssembly>true</skipAssembly>
        </configuration>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-shade-plugin</artifactId>
        <executions>
          <execution>
            <id>aggregate-into-a-jar-with-relocated-third-parties</id>
            <configuration>
              <artifactSet>
                <excludes>
                  <!-- Keep in sync with hbase-shaded-client -->
                  <exclude>javax.annotation:javax.annotation-api</exclude>
                  <exclude>javax.activation:javax.activation-api</exclude>
                  <exclude>jakarta.activation:jakarta.activation-api</exclude>
                  <exclude>jakarta.ws.rs:jakarta.ws.rs-api</exclude>
                  <exclude>jakarta.annotation:jakarta.annotation-api</exclude>
                  <exclude>jakarta.validation:jakarta.validation-api</exclude>
                  <exclude>org.glassfish.hk2.external:jakarta.inject</exclude>
                  <exclude>org.apache.hbase:hbase-resource-bundle</exclude>
                  <exclude>org.slf4j:*</exclude>
                  <exclude>com.google.code.findbugs:*</exclude>
                  <exclude>com.github.stephenc.findbugs:*</exclude>
                  <exclude>com.github.spotbugs:*</exclude>
                  <exclude>org.apache.htrace:*</exclude>
                  <exclude>org.apache.yetus:*</exclude>
                  <exclude>org.apache.logging.log4j:*</exclude>
                  <exclude>commons-logging:*</exclude>
                  <exclude>org.javassist:*</exclude>
                </excludes>
              </artifactSet>
              <relocations combine.children="append">
                <relocation>
                  <pattern>io.opentelemetry</pattern>
                  <shadedPattern>${shaded.prefix}.io.opentelemetry</shadedPattern>
                </relocation>
              </relocations>
              <filters combine.children="append">
                <filter>
                  <artifact>*:*</artifact>
                  <excludes>
                    <exclude>META-INF/services/javax.ws.rs.ext.MessageBodyReader</exclude>
                    <exclude>META-INF/services/javax.ws.rs.ext.MessageBodyWriter</exclude>
                    <exclude>META-INF/services/javax.ws.rs.ext.RuntimeDelegate</exclude>
                  </excludes>
                </filter>
              </filters>
            </configuration>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
</project>
